# Generated by Django 4.2.5 on 2023-09-07 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('channel', models.CharField(choices=[('youtube', 'Youtube'), ('odysee', 'Odysee')], max_length=15)),
                ('category', models.CharField(blank=True, choices=[('political', 'Politique'), ('economical', 'Economique'), ('spiritual', 'Spirituel'), ('belarus', 'Belarus')], max_length=12, null=True)),
                ('youtube_name', models.CharField(blank=True, max_length=60, null=True)),
                ('youtube_id', models.CharField(blank=True, max_length=40, null=True)),
                ('odysee_name', models.CharField(blank=True, max_length=60, null=True)),
                ('odysee_id', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profiles',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imported_3dom_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='movie',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='video3domapp.creator'),
            preserve_default=False,
        ),
    ]
