# Generated by Django 4.2.5 on 2023-09-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0002_creator_remove_customuser_profiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='created_original',
            new_name='created_in_3dom',
        ),
        migrations.AddField(
            model_name='movie',
            name='channel_external_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='movies'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='covers'),
        ),
    ]
