# Generated by Django 4.2.5 on 2023-09-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0003_rename_created_original_movie_created_in_3dom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='file_tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
