# Generated by Django 4.2.5 on 2023-09-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0004_movie_file_date_movie_file_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='category',
            field=models.CharField(blank=True, choices=[('political', 'Politique'), ('economical', 'Economique'), ('entertainment', 'Divertissement'), ('spiritual', 'Spirituel'), ('belarus', 'Belarus')], max_length=25, null=True),
        ),
    ]
