# Generated by Django 4.2.5 on 2023-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0005_alter_creator_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='rumble_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='creator',
            name='rumble_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='channel',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('odysee', 'Odysee'), ('rumble', 'Rumble')], max_length=15),
        ),
    ]
