# Generated by Django 4.2.5 on 2023-09-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0006_creator_rumble_id_creator_rumble_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
