# Generated by Django 4.2.5 on 2023-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0008_rename_file_url_movie_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
