# Generated by Django 4.2.5 on 2023-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0009_movie_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file_duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
