# Generated by Django 4.2.5 on 2023-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0010_alter_movie_file_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='channel',
            field=models.CharField(choices=[('youtube', 'Youtube'), ('local', 'Classique'), ('odysee', 'Odysee'), ('rumble', 'Rumble')], max_length=15),
        ),
    ]
