# Generated by Django 4.2.5 on 2023-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video3domapp', '0011_alter_creator_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='alternate_comment',
            field=models.BooleanField(default=False),
        ),
    ]
